title: Baol's little place on the Internet
email: baol@protonmail.ch
description: > # this means to ignore newlines until "baseurl:"
   Complex software needs no complicated solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "100allora.it" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ieghermaister
github_username:  baol

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
